name: PyInstaller Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build with PyInstaller Spec File
        run: |
          poetry run pyinstaller utils/bundle/bundle.spec

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist/
